apiVersion: v1
kind: Service
metadata:
  name: {{ include "lpnode-admin.fullname" . }}-server
spec:
  selector:
    app: {{ include "lpnode-admin.fullname" . }}
  type: ClusterIP
  ports:
    - protocol: TCP
      name: {{ include "lpnode-admin.fullname" . }}-api
      port: 18006
      targetPort: 18006