domain:
  name: ws.obridge-api-relay.edge-dev.xyz
redis:
  password_key: obridge-relay-db-redis
  host: obridge-relay-db-redis-master
  db: '5'
image:
  name: kldtks/edge:obridge-relay-fep-websocket-8bf82c87
