apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otmoic-lpnode-graphql.fullname" . }}
  labels:
    app: {{ include "otmoic-lpnode-graphql.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "otmoic-lpnode-graphql.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "otmoic-lpnode-graphql.fullname" . }}
    spec:
      containers:
      - name: {{ include "otmoic-lpnode-graphql.fullname" . }}
        image: {{ .Values.image.name }}
        ports:
          - containerPort: 18086
        env:
          - name: OBRIDGE_LPNODE_DB_REDIS_MASTER_SERVICE_HOST
            value: "obridge-lpnode-db-redis-master"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: obridge-lpnode-db-redis
                key: redis-password
          - name: LP_NODE_DATA_MONGO_URL
            value: "obridge-lpnode-db-mongodb"
          - name: LP_MARKET_SERVICE_URL
            value: "obridge-lpnode-market"
          - name: KUBERNETES_SERVICE_PORT_HTTPS
            value: 1000

