apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edge-desktop-rb
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  # kind: Role
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io