apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appconfig.appname }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appconfig.appname }}
  ports:
    - protocol: TCP
      port: {{ .Values.appconfig.portService }}
      targetPort: {{ .Values.appconfig.portPod }}
      nodePort: {{ .Values.appconfig.portExternal }}