apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
      - name: {{ $fullName }}
        image: {{ .Values.image.name }}
        ports:
          - containerPort: 9202
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: obridge-lpnode-db-redis
                key: redis-password
          - name: LPNODE_URI
            value: "{{ .Values.lpconfig.lpnode_uri }}"
          - name: RELAY_URI
            value: "{{ .Values.lpconfig.relay_uri }}"
