apiVersion: v1
kind: Service
metadata:
  name: lpnode-server
spec:
  selector:
    app: lpnode
  type: ClusterIP
  ports:
    - protocol: TCP
      name: lpnode-api
      port: 9202
      targetPort: 9202