apiVersion: v1
kind: Service
metadata:
  name: {{ include "obridge-lpnode.fullname" . }}-server
spec:
  selector:
    app: {{ include "obridge-lpnode.fullname" . }}
  type: ClusterIP
  ports:
    - protocol: TCP
      name: {{ include "obridge-lpnode.fullname" . }}-api
      port: 9202
      targetPort: 9202