apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-server
spec:
  selector:
    app: {{ $fullName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      name: {{ $fullName }}-api
      port: 9202
      targetPort: 9202