apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-obridge-web-app
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: "Host(`{{ .Values.domain.name }}`)"
      kind: Rule
      services:
        - name: web-app-server
          port: 9000