apiVersion: v1
kind: Service
metadata:
  name: chain-client-evm-server-{{ .Values.evm.system_chain_id }}
spec:
  selector:
    app: chain-client-evm-{{ .Values.evm.system_chain_id }}
  type: ClusterIP
  ports:
    - protocol: TCP
      name: chain-client-evm-api-{{ .Values.evm.system_chain_id }}
      port: 9100
      targetPort: 9100