apiVersion: v1
kind: Service
metadata:
  name: relay-adminpanel-service
spec:
  selector:
    app: relay-adminpanel
  type: ClusterIP
  ports:
    - protocol: TCP
      name: relay-admin-panel-api
      port: 9101
      targetPort: 9101