apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}"
spec:
  rules:
    - host: "{{.Values.domain.name }}"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: amm-server
              port:
                number: 18081
     
