apiVersion: v1
kind: Service
metadata:
  name: web-app-server
spec:
  selector:
    app: web-app
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web-app-api
      port: 9000
      targetPort: 9000