apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-fep-websocket-1
  labels:
    app: relay-fep-websocket-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relay-fep-websocket-1
  template:
    metadata:
      labels:
        app: relay-fep-websocket-1
    spec:
      containers:
      - name: relay-fep-websocket-1
        image: {{ .Values.image.name }}
        ports:
          - containerPort: 3000
          - containerPort: 3001
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: obridge-relay-db-redis
                key: redis-password
          - name: REDIS_HOST
            value: "{{ .Values.redis.host }}"
          - name: REDIS_DB
            value: "{{ .Values.redis.db }}"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP         
          - name: SERVER_NAME
            value: relay-fep-ws-server-1
          - name: CORS_ORIGIN
            value: "{{ .Values.ws.cors.origin }}"
          - name: URL_COOKIE_MATH
            value: "{{ .Values.ws.url_cookie_math }}"
          - name: DOMAIN
            value: "{{ .Values.ws.cookie.domain }}" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-fep-websocket-2
  labels:
    app: relay-fep-websocket-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-fep-websocket-2
  template:
    metadata:
      labels:
        app: relay-fep-websocket-2
    spec:
      containers:
      - name: relay-fep-websocket-2
        image: {{ .Values.image.name }}
        ports:
          - containerPort: 3000
          - containerPort: 3001
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: obridge-relay-db-redis
                key: redis-password
          - name: REDIS_HOST
            value: "{{ .Values.redis.host }}"
          - name: REDIS_DB
            value: "{{ .Values.redis.db }}"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP         
          - name: SERVER_NAME
            value: relay-fep-ws-server-2
          - name: CORS_ORIGIN
            value: "{{ .Values.ws.cors.origin }}"
          - name: URL_COOKIE_MATH
            value: "{{ .Values.ws.url_cookie_math }}"
          - name: DOMAIN
            value: "{{ .Values.ws.cookie.domain }}" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-fep-websocket-3
  labels:
    app: relay-fep-websocket-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-fep-websocket-3
  template:
    metadata:
      labels:
        app: relay-fep-websocket-3
    spec:
      containers:
      - name: relay-fep-websocket-3
        image: {{ .Values.image.name }}
        ports:
          - containerPort: 3000
          - containerPort: 3001
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: obridge-relay-db-redis
                key: redis-password
          - name: REDIS_HOST
            value: "{{ .Values.redis.host }}"
          - name: REDIS_DB
            value: "{{ .Values.redis.db }}"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP         
          - name: SERVER_NAME
            value: relay-fep-ws-server-3
          - name: CORS_ORIGIN
            value: "{{ .Values.ws.cors.origin }}"
          - name: URL_COOKIE_MATH
            value: "{{ .Values.ws.url_cookie_math }}"
          - name: DOMAIN
            value: "{{ .Values.ws.cookie.domain }}"  