apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-obridge-relay-fep-websocket-redirect
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: "Host(`{{ .Values.domain.name }}`) && PathPrefix(`/connect`)"
      kind: Rule
      services:
        - name: relay-fep-ws-loadbalance-server-redirect
          kind: TraefikService
          passHostHeader: true