apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-obridge-relay-fep-websocket
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: "Host(`{{ .Values.domain.name }}`)"
      kind: Rule
      services:
        - name: relay-fep-ws-loadbalance-server
          kind: TraefikService
          passHostHeader: true
          sticky:
              cookie:
                httpOnly: true
                name: lvl1
                sameSite: none
                secure: true