apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: relay-fep-ws-loadbalance-server
spec:
  weighted:
    services:
      - name: relay-fep-ws-server-1
        kind: Service
        port: 3000
        passHostHeader: true
        weight: 1
        sticky:
          cookie:
            name: server_id
            httpOnly: true
      - name: relay-fep-ws-server-2
        kind: Service
        weight: 1
        port: 3000
        passHostHeader: true
        sticky:
          cookie:
            name: server_id
            httpOnly: true
      - name: relay-fep-ws-server-3
        kind: Service
        weight: 1
        port: 3000
        passHostHeader: true
        sticky:
          cookie:
            name: server_id
            httpOnly: true
    sticky:
      cookie:
        name: lvl1