domain:
  name: obridge-api-lpnode.edge-dev.xyz
lpconfig:
  lpnode_uri: https://obridge-api-lpnode.edge-dev.xyz/lpnode
  relay_uri: https://obridge-api-relay.edge-dev.xyz/relay
image:
  name: kldtks/edge:obridge-lpnode-eaba6a3c
