apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-server"
spec:
  selector:
    app: "{{.Release.Name }}"
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "{{ .Release.Name }}-api"
      port: 18080
      targetPort: 18080
